config/routes.rb
Banter::Application.routes.draw do
  
  resources :rooms
  root to: "rooms#index"

end 

app/models/message.rb
class Message < ActiveRecord::Base
  attr_accessible :body, :name, :photo_url, :provider, :provider_id, :room_id

	belongs_to :room

	validates :body, presence: true
	validates :name, presence: true
end

app/models/room.rb
class Room < ActiveRecord::Base
  attr_accessible :title, :url

  has_many :messages

  acts_as_url :title

  validates :title, presence: true, uniqueness: true

  def to_param
  	url
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/index_controller.rb
class IndexController < ApplicationController
  def show
  end

  def new
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def index
	@rooms = Room.all
  end

  def show
  	@room = Room.find_by_url(params[:id])
  end

  def new
  	@room = Room.new
  end

  def create
	@room = Room.new(params[:room])
	if @room.save
		flash[:success] = "yay, we've created  a room"
		redirect_to room_path(@room)
	else
		render "new"
	end

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/index/new.html.erb
<h1>Index#new</h1>
<p>Find me in app/views/index/new.html.erb</p>

app/views/index/show.html.erb
<h1>Index#show</h1>
<p>Find me in app/views/index/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Banter</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/rooms/_message.html.erb
<div class="message">
	<h3><%= message.name %> says</h3>

	<%= simple_format message.body %>
</div>

app/views/rooms/index.html.erb
<h2>Rooms</h2>

<% @rooms.each do |r| %>

	<h3><%= link_to r.title, room_path(r) %></h3>

<% end %>

<p><%= link_to "create new room", new_room_path, class: "button" %></p>

app/views/rooms/new.html.erb
<h2>Create new room</h2>

<%= simple_form_for @room do |f| %>

	<%= f.input :title, placeholder: "e.g. Dom's Banter" %>

	<%= f.button :submit, "Go" %>

<% end %>

app/views/rooms/show.html.erb
<h2><%= @room.title %></h2>

	<%= render partial: "message", collection: @room.messages %>